apiVersion: v1
kind: Service
metadata:
  name: {{ include "lingochat.socketFullname" . }}-svc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lingochat.labels" . | nindent 4 }}
    app: {{ include "lingochat.socketFullname" . }}
spec:
  type: {{ .Values.socket.service.type }}
  ports:
    - port: {{ .Values.socket.service.port }}
      targetPort: {{ .Values.socket.service.targetPort }}
      protocol: TCP
  selector:
    {{- include "lingochat.selectorLabels" . | nindent 4 }}
    app: {{ include "lingochat.socketFullname" . }}
