{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lingo-nginx-ingress
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.ingress.nginxServiceName }}
            port:
              number: {{ .Values.nginx.service.port }}
      - path: /api/(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .Values.ingress.apiServiceName }}
            port:
              number: {{ .Values.api.service.port }}
      - path: /socket/(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .Values.ingress.socketServiceName }}
            port:
              number: {{ .Values.socket.service.port }}
      - path: /socket.io/(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .Values.ingress.socketServiceName }}
            port:
              number: {{ .Values.socket.service.port }}
{{- end }}
