apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lingochat.labels" . | nindent 4 }}
spec:
  capacity:
    storage: {{ .Values.nginx.storage.nfs.size }}
  accessModes:
    - ReadWriteMany
  nfs:
    server: {{ .Values.nginx.storage.nfs.server }}
    path: {{ .Values.nginx.storage.nfs.path }}
