apiVersion: v1
kind: Service
metadata:
  name: {{ include "lingochat.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lingochat.labels" . | nindent 4 }}
spec:
  type: {{ .Values.nginx.service.type }}
  ports:
    - port: {{ .Values.nginx.service.port }}
      targetPort: {{ .Values.nginx.service.port }}
      protocol: TCP
      name: webui
  selector:
    {{- include "lingochat.selectorLabels" . | nindent 4 }}
