apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lingochat.apiFullname" . }}-deploy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lingochat.labels" . | nindent 4 }}
    app: {{ include "lingochat.apiFullname" . }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "lingochat.selectorLabels" . | nindent 6 }}
      app: {{ include "lingochat.apiFullname" . }}
  template:
    metadata:
      annotations:
        {{- if .Values.api.vault.enabled }}
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "api-account"
        vault.hashicorp.com/agent-inject-secret-api-secrets: "{{ .Values.api.vault.secretPath }}"
        vault.hashicorp.com/agent-inject-template-api-secrets: |
          {{`{{- with secret "`}}{{ .Values.api.vault.secretPath }}{{`" -}}`}}
          export POSTGRESQL_USER="{{`{{ .Data.data.POSTGRESQL_USER }}`}}"
          export POSTGRESQL_PASSWORD="{{`{{ .Data.data.POSTGRESQL_PASSWORD }}`}}"
          export OAUTH_GOOGLE_CLIENT_ID="{{`{{ .Data.data.OAUTH_GOOGLE_CLIENT_ID }}`}}"
          export OAUTH_GOOGLE_SECRET="{{`{{ .Data.data.OAUTH_GOOGLE_SECRET }}`}}"
          export JWT_ACCESS_SECRET_KEY="{{`{{ .Data.data.JWT_ACCESS_SECRET_KEY }}`}}"
          export JWT_REFRESH_SECRET_KEY="{{`{{ .Data.data.JWT_REFRESH_SECRET_KEY }}`}}"
          {{`{{- end -}}`}}
        {{- end }}
      labels:
        {{- include "lingochat.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        app: {{ include "lingochat.apiFullname" . }}
    spec:
      serviceAccountName: {{ .Values.api.serviceAccountName }}
      containers:
        - name: {{ .Chart.Name }}-api
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: api-config
          ports:
            - containerPort: {{ .Values.api.service.targetPort }}

